

-- *IMPORTANT* Before inserting the following, Create 4 users using the application.

INSERT INTO "projects" ("name", "country_id", "user_id") VALUES ('test1', 2, 1);
INSERT INTO "projects" ("name", "country_id", "user_id") VALUES ('test2', 21,4);
INSERT INTO "projects" ("name", "country_id", "user_id") VALUES ('test3', 19, 1);
INSERT INTO "projects" ("name", "country_id", "user_id") VALUES ('Protect the Lions', 15, 3);
INSERT INTO "projects" ("name", "country_id", "user_id") VALUES ('Safe Tiger', 16, 3);
INSERT INTO "projects" ("name", "country_id", "user_id") VALUES ('Bears, Bears, Bears!', 104, 3);
INSERT INTO "projects" ("name", "country_id", "user_id") VALUES ('Whale of a Project', 92, 2);
INSERT INTO "projects" ("name", "country_id", "user_id") VALUES ('Clean the Ocean', 100, 2);

INSERT INTO "project_type" ("project_id", "type_id") VALUES (1, 3);
INSERT INTO "project_type" ("project_id", "type_id") VALUES (2, 7);
INSERT INTO "project_type" ("project_id", "type_id") VALUES (3, 5);
INSERT INTO "project_type" ("project_id", "type_id") VALUES (4, 4);
INSERT INTO "project_type" ("project_id", "type_id") VALUES (5, 2);
INSERT INTO "project_type" ("project_id", "type_id") VALUES (6, 1);
INSERT INTO "project_type" ("project_id", "type_id") VALUES (7, 6);
INSERT INTO "project_type" ("project_id", "type_id") VALUES (8, 8);
INSERT INTO "project_type" ("project_id", "type_id") VALUES (2, 9);
INSERT INTO "project_type" ("project_id", "type_id") VALUES (6, 10);
INSERT INTO "project_type" ("project_id", "type_id") VALUES (4, 11);
INSERT INTO "project_type" ("project_id", "type_id") VALUES (1, 12);


INSERT INTO "footprints" ("project_id", "period") VALUES (1,'2016-08-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4,'2016-11-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-08-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-11-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (6, '2016-12-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (8, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-08-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-11-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-02-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (2, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-12-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-10-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-02-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-04-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4,'2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-11-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (6, '2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (6, '2016-10-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (8, '2016-04-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-12-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-11-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (6, '2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-08-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (8, '2016-07-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (6, '2016-12-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-07-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (8, '2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (8, '2016-10-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (6, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (6, '2016-04-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-12-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (3, '2016-11-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-06-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-12-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-04-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-06-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-11-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-12-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-04-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-06-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-11-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-12-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-04-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (8, '2016-12-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (6, '2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (6, '2016-12-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (8, '2016-04-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-10-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-11-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-12-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-04-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (5, '2016-05-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (4, '2016-11-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (7, '2016-09-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (6, '2016-05-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (6, '2016-03-01');
INSERT INTO "footprints" ("project_id", "period") VALUES (6, '2016-04-01');


INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 100, 13, 4);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (350, 40, 100, 13, 8);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (380, 40, 100, 13, 9);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 100, 13, 10);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (370, 40, 100, 13,11);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 141, 100, 13, 12);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 4, 100, 13, 13);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 543, 100, 13, 14);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 234, 100, 13, 15);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 43, 100, 13, 16);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 7666, 543, 13, 17);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 67, 100, 13, 18);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 234, 13, 19);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 55, 13, 20);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 100, 13, 21);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 433, 13, 22);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 100, 13, 23);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (432, 40, 100, 13, 24);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (55, 543, 100, 13, 25);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 26);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 100, 13, 27);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (350, 40, 100, 13, 28);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (380, 40, 100, 13, 29);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 100, 13, 30);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (370, 40, 100, 13, 31);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 141, 100, 13, 32);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 4, 100, 13, 33);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 543, 100, 13, 34);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 234, 100, 13, 35);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 43, 100, 13, 36);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 7666, 543, 13, 37);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 67, 100, 13, 38);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 234, 13, 39);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 55, 13, 40);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 100, 13, 41);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 433, 13, 42);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 40, 100, 13, 43);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (432, 40, 100, 13, 44);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (55, 543, 100, 13, 45);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 132, 46);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 432, 13, 47);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 22, 13, 48);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 49);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 543, 13, 50);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 543, 13, 51);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 52);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 34, 13, 53);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 54, 13, 54);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 55);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 34, 13, 56);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (45, 23, 100, 13, 57);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 58);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 1123, 13, 59);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 60);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (43, 3, 32, 13, 61);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 432, 13, 62);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 324, 100, 13, 63);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 654, 64);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 65);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (543, 23, 432, 13, 66);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 654, 100, 4, 67);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 68);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 324, 100, 13, 69);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 654, 70);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 71);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (543, 23, 432, 13, 72);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 654, 100, 4, 73);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 74);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 75);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 5);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 6);
INSERT INTO "living" ("hotel", "fuel", "grid", "propane", "footprint_id") VALUES (30, 23, 100, 13, 7);


INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (45, 40, 13, 23, 4);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 432, 3, 5);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (534, 54, 76, 143, 6);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 342, 7);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 34, 13, 65, 8);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 3, 654, 9);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 543, 13, 12, 10);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 32, 11);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 432, 12);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (12, 54, 87, 23, 13);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 54, 14);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 432, 432, 234, 15);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (3320, 40, 13, 54, 16);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 3, 13, 543, 17);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (3320, 40, 13,23, 18);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 405, 13, 66, 19);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 23, 20);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 43, 21);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (43, 40, 13, 54, 22);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 33, 23);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 654, 22, 24);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (543, 34, 13, 44, 25);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 153, 54, 26);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 34, 27);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (350, 40, 153, 22,28);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 5, 39);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (350, 450, 13, 34, 40);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 5, 41);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (350, 40, 13, 3, 42);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (330, 40, 13, 0, 43);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 143, 0, 44);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 22, 45);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (350, 4340, 13, 59, 46);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 133, 33, 47);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 543, 13, 55, 48);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 66, 49);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 234, 213, 3, 50);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 423, 13, 54, 51);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 43, 33, 52);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (234, 40, 13, 22, 53);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 543, 13, 11, 54);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 5, 55);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 4, 56);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 45, 66, 57);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (65, 40, 13, 33, 58);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 654, 45, 2, 59);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 55, 60);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 444, 61);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (76, 877, 13, 22, 62);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 11, 645, 55, 63);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 11, 64);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 44, 65);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (55, 44, 654, 22, 66);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 54, 18, 67);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 4, 13, 22, 68);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (654, 40, 13, 11, 69);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 456, 13, 44, 70);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 82, 71);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (45, 40, 13, 22, 72);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 654, 11, 73);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 5, 74);
INSERT INTO "shipping" ("air", "truck", "sea", "freight_train", "footprint_id") VALUES (30, 40, 13, 8, 75);


INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 4);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 45, 163, 5);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (654, 40, 13, 6);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 7);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 65, 8);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 9);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (430, 654, 13, 10);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 440, 13, 11);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 123, 12);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 450, 13, 13);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 153, 14);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (360, 40, 13, 15);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 16);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (306, 40, 153, 17);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 18);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (543, 40, 13, 19);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 543, 13, 20);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 987, 13, 21);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 22);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (654, 40, 34, 23);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 987, 13, 24);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (78, 40, 13, 25);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (32, 432, 13, 26);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 113, 43);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 543, 13, 28);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 444, 29);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 432, 13, 30);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (360, 40, 13, 31);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 87, 13, 32);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 21, 32, 33);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 43, 34);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (760, 6, 13, 35);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 4, 36);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (305, 40, 13, 37);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (21, 40, 13, 38);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (380, 876, 13, 39);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 321, 40);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (1, 40, 12, 41);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 645, 42);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (530, 40, 13, 43);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 44);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (330, 40, 13, 45);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 45, 13, 46);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (23, 40, 654, 47);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 48);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (430, 654, 13, 49);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 65, 13, 50);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 23, 51);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (432, 23, 13, 52);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 53);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 54);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 23, 432, 55);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (532, 40, 13, 56);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 57);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 43, 432, 58);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (23, 40, 13, 59);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 543, 13, 60);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (222, 40, 13, 61);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 65, 13, 62);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (432, 40, 13, 63);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 64);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 54, 13, 65);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 432, 66);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 32, 67);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (432, 40, 13, 68);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 69);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (23, 40, 43, 70);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 34, 13, 71);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 72);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (432, 40, 23, 73);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 40, 13, 74);
INSERT INTO "travel" ("plane", "car", "train", "footprint_id") VALUES (30, 423, 13, 75);
